# avi:
#   password: Avi_2020

user:
  - name: ansible
    is_superuser: true
    user_profile_ref: "/api/useraccountprofile?name=Default-User-Account-Profile"
    is_active: true
    default_tenant_ref: "/api/tenant?name=admin"
    access:
      - role_ref: "/api/role?name=System-Admin"
        tenant_ref: "/api/tenant/admin#admin"
      - all_tenants: true
        role_ref: "/api/role?name=System-Admin"
    credsJsonFile: ~/creds/aviLsc/ansible.json
  - name: terraform
    is_superuser: true
    user_profile_ref: "/api/useraccountprofile?name=Default-User-Account-Profile"
    is_active: true
    default_tenant_ref: "/api/tenant?name=admin"
    access:
      - role_ref: "/api/role?name=System-Admin"
        tenant_ref: "/api/tenant/admin#admin"
      - all_tenants: true
        role_ref: "/api/role?name=System-Admin"
    credsJsonFile: ~/creds/aviLsc/terraform.json
  - name: python
    is_superuser: true
    user_profile_ref: "/api/useraccountprofile?name=Default-User-Account-Profile"
    is_active: true
    default_tenant_ref: "/api/tenant?name=admin"
    access:
      - role_ref: "/api/role?name=System-Admin"
        tenant_ref: "/api/tenant/admin#admin"
      - all_tenants: true
        role_ref: "/api/role?name=System-Admin"
    credsJsonFile: ~/creds/aviLsc/python.json
  - name: vrovra
    is_superuser: true
    user_profile_ref: "/api/useraccountprofile?name=Default-User-Account-Profile"
    is_active: true
    default_tenant_ref: "/api/tenant?name=admin"
    access:
      - role_ref: "/api/role?name=System-Admin"
        tenant_ref: "/api/tenant/admin#admin"
      - all_tenants: true
        role_ref: "/api/role?name=System-Admin"
    credsJsonFile: ~/creds/aviLsc/vrovra.json

# credsJsonFile:
#   - ../aviLscCloud/vars/creds.json
