avi:
  password: Avi_2020

user:
  - name: ansible
    is_superuser: true
    user_profile_ref: "/api/useraccountprofile?name=Default-User-Account-Profile"
    is_active: true
    default_tenant_ref: "/api/tenant?name=admin"
    access:
      - role_ref: "/api/role?name=System-Admin"
        tenant_ref: "/api/tenant/admin#admin"
      - all_tenants: true
        role_ref: "/api/role?name=System-Admin"
    credsJsonFile: ../aviLscCloud/vars/creds.json
  - name: terraform
    is_superuser: true
    user_profile_ref: "/api/useraccountprofile?name=Default-User-Account-Profile"
    is_active: true
    default_tenant_ref: "/api/tenant?name=admin"
    access:
      - role_ref: "/api/role?name=System-Admin"
        tenant_ref: "/api/tenant/admin#admin"
      - all_tenants: true
        role_ref: "/api/role?name=System-Admin"
    credsJsonFile: ../../terraform/aviVs/creds.tfvars.json
  - name: python
    is_superuser: true
    user_profile_ref: "/api/useraccountprofile?name=Default-User-Account-Profile"
    is_active: true
    default_tenant_ref: "/api/tenant?name=admin"
    access:
      - role_ref: "/api/role?name=System-Admin"
        tenant_ref: "/api/tenant/admin#admin"
      - all_tenants: true
        role_ref: "/api/role?name=System-Admin"
    credsJsonFile: ../../python/aviVs/creds.json
  - name: vrovra
    is_superuser: true
    user_profile_ref: "/api/useraccountprofile?name=Default-User-Account-Profile"
    is_active: true
    default_tenant_ref: "/api/tenant?name=admin"
    access:
      - role_ref: "/api/role?name=System-Admin"
        tenant_ref: "/api/tenant/admin#admin"
      - all_tenants: true
        role_ref: "/api/role?name=System-Admin"

avi_systemconfiguration:
  global_tenant_config:
    se_in_provider_context: true
    tenant_access_to_provider_se: true
    tenant_vrf: true
  welcome_workflow_complete: true
  ntp_configuration:
    ntp_servers:
      - server:
          type: V4
          addr: 192.168.10.3
  dns_configuration:
    search_domain: ''
    server_list:
      - type: V4
        addr: 8.8.8.8
      - type: V4
        addr: 4.4.4.4
  email_configuration:
    from_email: test@avicontroller.net
    smtp_type: SMTP_LOCAL_HOST

credsJsonFile:
  - ../aviLscCloud/vars/creds.json
